export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const EMPTY_CART = "EMPTY_CART";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";
